/*
 * TestMatissePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package forward;

/**
 *
 * @author  __USER__
 */
public class TestMatissePanel extends javax.swing.JPanel {

	/** Creates new form TestMatissePanel */
	public TestMatissePanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable5 = new javax.swing.JTable();
		jButton2 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jPanel2 = new javax.swing.JPanel();
		jSlider1 = new javax.swing.JSlider();

		setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		setToolTipText("Main");
		setMinimumSize(new java.awt.Dimension(200, 150));
		setPreferredSize(new java.awt.Dimension(300, 250));
		setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

		jPanel3.setToolTipText("Top grid service flow");
		jPanel3.setMaximumSize(new java.awt.Dimension(280, 122));
		jPanel3.setMinimumSize(new java.awt.Dimension(280, 122));
		jPanel3.setOpaque(false);
		jPanel3.setPreferredSize(new java.awt.Dimension(280, 122));
		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5,
				0));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
		jPanel4.setToolTipText("top grid bag");
		jPanel4.setMaximumSize(new java.awt.Dimension(280, 122));
		jPanel4.setMinimumSize(new java.awt.Dimension(280, 122));
		jPanel4.setPreferredSize(new java.awt.Dimension(280, 122));
		jPanel4.setVerifyInputWhenFocusTarget(false);
		jPanel4.setLayout(new java.awt.GridBagLayout());

		jScrollPane5.setForeground(new java.awt.Color(255, 255, 102));
		jScrollPane5
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane5
				.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
		jScrollPane5.setInheritsPopupMenu(true);
		jScrollPane5.setMaximumSize(new java.awt.Dimension(200, 100));
		jScrollPane5.setMinimumSize(new java.awt.Dimension(200, 100));
		jScrollPane5.setOpaque(false);
		jScrollPane5.setPreferredSize(new java.awt.Dimension(200, 100));

		jTable5.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {
						{ "A", "a", new Boolean(true), new Integer(1) },
						{ "B", "b", new Boolean(true), new Integer(2) },
						{ "C", "c", null, new Integer(3) },
						{ "D", "d", new Boolean(true), new Integer(4) } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.Boolean.class,
					java.lang.Integer.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jTable5.setMaximumSize(new java.awt.Dimension(200, 100));
		jTable5.setMinimumSize(new java.awt.Dimension(200, 100));
		jTable5.setOpaque(false);
		jTable5.setPreferredSize(new java.awt.Dimension(200, 100));
		jScrollPane5.setViewportView(jTable5);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(22, 0, 0, 0);
		jPanel4.add(jScrollPane5, gridBagConstraints);

		jButton2.setText("jButton2");
		jButton2.setMaximumSize(new java.awt.Dimension(60, 25));
		jButton2.setMinimumSize(new java.awt.Dimension(60, 25));
		jButton2.setPreferredSize(new java.awt.Dimension(60, 25));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		jPanel4.add(jButton2, gridBagConstraints);

		jPanel3.add(jPanel4);

		add(jPanel3);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 0, 255)));
		jPanel1.setToolTipText("Top");
		jPanel1.setAutoscrolls(true);
		jPanel1.setMaximumSize(new java.awt.Dimension(280, 120));
		jPanel1.setMinimumSize(new java.awt.Dimension(280, 120));
		jPanel1.setPreferredSize(new java.awt.Dimension(280, 10));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jTextField1.setText("jTextField1");
		jTextField1.setDoubleBuffered(true);
		jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
		jTextField1.setMinimumSize(new java.awt.Dimension(120, 20));
		jTextField1.setOpaque(false);
		jTextField1.setPreferredSize(new java.awt.Dimension(120, 20));
		jTextField1.setRequestFocusEnabled(false);
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.ipadx = 10;
		gridBagConstraints.ipady = 9;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weighty = 10.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(jTextField1, gridBagConstraints);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox1.setMaximumSize(new java.awt.Dimension(32767, 10));
		jComboBox1.setMinimumSize(new java.awt.Dimension(55, 10));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
		jPanel1.add(jComboBox1, gridBagConstraints);

		jLabel2.setText("Label lunga quanto basta per");
		jLabel2.setMaximumSize(new java.awt.Dimension(120, 10));
		jLabel2.setMinimumSize(new java.awt.Dimension(120, 10));
		jLabel2.setPreferredSize(new java.awt.Dimension(120, 10));
		jLabel2.setRequestFocusEnabled(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(jLabel2, gridBagConstraints);

		jCheckBox1.setText("jCheckBox1");
		jCheckBox1.setMaximumSize(new java.awt.Dimension(135, 25));
		jCheckBox1.setMinimumSize(new java.awt.Dimension(135, 25));
		jCheckBox1.setPreferredSize(new java.awt.Dimension(135, 20));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		jPanel1.add(jCheckBox1, gridBagConstraints);

		add(jPanel1);

		jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1,
				1, new java.awt.Color(0, 0, 102)));
		jPanel2.setMaximumSize(new java.awt.Dimension(280, 50));
		jPanel2.setMinimumSize(new java.awt.Dimension(280, 50));
		jPanel2.setOpaque(false);
		jPanel2.setPreferredSize(new java.awt.Dimension(280, 50));
		jPanel2.setLayout(new java.awt.CardLayout());
		jPanel2.add(jSlider1, "card2");

		add(jPanel2);
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JSlider jSlider1;
	private javax.swing.JTable jTable5;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}